-- local jvim = require('jvim')
--
-- vim.keymap.set('n', '<Left>', jvim.to_parent, {noremap = true, silent = true})
-- vim.keymap.set('n', '<Right>', jvim.descend, {noremap = true, silent = true})
-- vim.keymap.set('n', '<Up>', jvim.prev_sibling, {noremap = true, silent = true})
-- vim.keymap.set('n', '<Down>', jvim.next_sibling, {noremap = true, silent = true})
