-- npm i -g vscode-langservers-extracted
return {
	cmd = { 'vscode-eslint-language-server', '--stdio' },
	filetypes = {
		'javascript',
		'javascriptreact',
		'javascript.jsx',
		'typescript',
		'typescriptreact',
		'typescript.tsx',
		'vue',
		'svelte',
		'astro',
	},
	root_markers = { 'package.json', '.git', 'js' },
	settings = {
		validate = 'on',
		packageManager = nil,
		useESLintClass = false,
		experimental = { useFlatConfig = false },
		codeActionOnSave = { enable = false, mode = 'all' },
		format = true,
		quiet = false,
		onIgnoredFiles = 'off',
		rulesCustomizations = {},
		run = 'onType',
		problems = { shortenToSingleLine = false },
		nodePath = '',
		workingDirectory = { mode = 'location' },
		codeAction = {
			disableRuleComment = { enable = true, location = 'separateLine' },
			showDocumentation = { enable = true },
		},
	},
}
