#!/usr/bin/env bash

# BREW (CASK)
echo "updating and upgrading Brew..."
brew update
brew upgrade

# NPM
echo "updating and upgrading NPM..."
npm install npm -g
npm update -g

# PIP
echo "updating and upgrading PIP..."
pip freeze > requirements.txt
pip install -r requirements.txt --upgrade
rm requirements.txt

# ATOM
echo "updating Atom packages..."
apm update

# APP STORE
echo "App Store software updates..."
sudo softwareupdate -i -a
