#!/usr/bin/env bash

reset=$(tput sgr0);
orangebold=$(tput bold; tput setaf 166);

# BREW (CASK)
echo -e "${orangebold}updating and upgrading Brew...${reset}"
brew update
brew upgrade

# NPM
echo -e "${orangebold}updating and upgrading NPM...${reset}"
npm install npm -g
npm update -g

# PIP
echo -e "${orangebold}updating and upgrading PIP...${reset}"
pip freeze > requirements.txt
pip install -r requirements.txt --upgrade -q
rm requirements.txt

# ATOM
echo -e "${orangebold}updating Atom packages...${reset}"
apm update

# APP STORE
echo "App Store software updates..."
sudo softwareupdate -i -a
