#!/usr/bin/env bash

# first clone the bare repo in .dot directory
git clone --bare "https://github.com/yochem/dotfiles.git" "$HOME/.dot"

# create function to use dot as alias more times
dot() {
    git --git-dir="$HOME/.dot/" --work-tree="$HOME" "$@"
}

# checkout gets the workingtree files
dot checkout

# if git checkout returned an error, create a backup and replace
if [ $? -ne 0 ]; then
    # grep only the listed files
    files=$(dot checkout 2>&1 | grep -E "^\s+" | awk {'print $1'})
    # loop over the files
    for file in "$files"; do
	# create directories if needed
	mkdir -p "$HOME/dotfiles-backup/$file"
	# mv the file to the place just created
	mv "$file" "$_"
    done
    echo "some files already exist on your computer. They have been moved to $HOME/dotfiles-backup."
fi

# checkout again to really do the checkout
dot checkout

# don't show untracked files
dot config status.showUntrackedFiles no

# let the user know whats up
echo "dotfiles installed. You might need to restart your terminal."
