#!/usr/bin/env bash

# first clone the bare repo in .dot directory
![ -d "$HOME/.dot" ] && git clone --bare https://github.com/yochem/dotfiles.git "$HOME/.dot"

# create alias to work with for now this seperates the work tree and git dir
alias dot="git --git-dir=\"$HOME/.dot/\" --work-tree=\"$HOME\""

# checkout gets the working tree files
dot checkout

# if git checkout returned an error, create a backup and replace
if [[ $? -ne 0 ]]; then
    files=$(dot checkout 2>&1 | grep -E "^\s+" | awk {'print $1'})
    for file in $files; do
	mkdir -p "$HOME/dotfiles-backup/$file"
	mv $file $_
    done
    echo "some files already exist on your computer. They have been moved to $HOME/dotfiles-backup."
fi

# don't show untracked files
dot config status.showUntrackedFiles no

# let the user know whats up
echo "dotfiles installed. You might need to restart your terminal."
