#!/usr/bin/env bash

# open python server
server() { s="${1:-8000}"; open "http://localhost:$s" && python3 -m http.server "$s"; }
phpserver() { open "http://localhost:$1" && php -S "localhost:$1"; }

# search something on youtube
yt() { open "https://www.youtube.com/results?search_query=${@// /+}"; }

# make a directory and cd into it
mkcd() { mkdir "$1"; cd "$1"; }

# open a manual as pdf
manpdf() { man -t "$1" | open -f -a /Applications/Preview.app/; }

# move to trash
thrash() { mv -f "$1" "$HOME/.Trash/$1"; }

# grep with color but output all lines
highlight() { grep --color -i -E "$1|$"; }

# go to a selected directory from the z data file
fzfz() { builtin cd $(z | fzf | awk '{print $2}');  }

# View the local git repository on Github
# Uses alias 'git url', as seen in git/.gitconfig
# 'open' opens an url in the browser on macOS. Not tested on linux
viewgh() {
    remote=$(git ls-remote --get-url origin)
    # format: https://github.com/USER/REPO.git
    if [[ ${remote:0:4} == "http" ]]; then
	open "${remote}"
    # format: git://github.com/USER/REPO.git
    elif [[ ${remote:0:4} == "git:" ]]; then
        open "https${remote:3}"
    # format: git@github.com:USER/REPO.git
    else
        open "https:$(echo ${remote:4} | tr : /)"
    fi
}

# use the same alias for all git repos
# before I used 'dot' as alias for my dotfiles repo but that's way to confusing
g() {
    if git status &>/dev/null; then
        git "$@"
    else
        git --git-dir="$HOME/.dot/" --work-tree="$HOME" "$@"
    fi
}

# gi macos gives the gitignore for macos.
# Use gi macos >> .gitignore to make file
gi() { curl -L -s "https://www.gitignore.io/api/$@"; }

# echo your computers ip-address
ip() { ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'; }

# usage: clone_all_from users/username or clone_all_from orgs/orgname
clone_all_from() {
    PAGE=1;
    curl "https://api.github.com/$@/repos?page=$PAGE&per_page=100" |
    grep -e 'git_url*' |
    cut -d \" -f 4 |
    xargs -L1 -P5 git clone;
}
