#!/usr/bin/env bash

# choose the default editor
if command -v nvim >/dev/null 2>&1; then
    export VISUAL="nvim"
elif command -v vim >/dev/null 2>&1; then
    export VISUAL="vim"
else
    export VISUAL="nano"
fi

export EDITOR="$VISUAL"


# add GNU core utils from brew to path
export PATH="/Library/TeX/texbin:$PATH"
export PATH="/Users/Yochem/Library/Python/3.7/bin:$PATH"
export PATH="/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/bin:$PATH"
export PATH="/bin:$PATH"
export PATH="/sbin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/sbin:$PATH"
export PATH="$HOME/.nvm/versions/node/v8.11.1/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/bin:$PATH"

# set path to node_modules
export NODE_PATH='/usr/local/lib/node_modules'

# increase bash history size
export HISTSIZE="32768"

# don't put duplicates in history
HISTCONTROL=ignoreboth

# don't let Terminal.app write session history
# (https://stackoverflow.com/questions/32418438/how-can-i-disable-bash-sessions-in-os-x-el-capitan)
SHELL_SESSION_HISTORY=0

export ATOM_HOME="$HOME/.config/atom"
export NLTK_DATA="$HOME/.local/share/nltk_data"
