#!/usr/bin/env bash

# choose the default editor
if command -v nvim >/dev/null 2>&1; then
    export VISUAL="nvim"
elif command -v vim >/dev/null 2>&1; then
    export VISUAL="vim"
else
    export VISUAL="nano"
fi

export EDITOR="$VISUAL"

# view manpage in neovim
export MANPAGER='nvim +Man!'

# use the macos open command as browser
export BROWSER="open"

# add local bin to path
export PATH="$HOME/.local/bin:$PATH"

# increase bash history size
export HISTSIZE="32768"

# add time stamp to bash history
export HISTTIMEFORMAT="%c "

# don't put duplicates in history
HISTCONTROL=ignoreboth

# don't let Terminal.app write session history
# (https://stackoverflow.com/questions/32418438/how-can-i-disable-bash-sessions-in-os-x-el-capitan)
SHELL_SESSION_HISTORY=0
