#!/usr/bin/env bash

# because some apps love to have their config files in the home directory,
# but I don't
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

export ATOM_HOME="$XDG_CONFIG_HOME/atom"
export NLTK_DATA="$XDG_DATA_HOME/nltk"
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
export LESSHISTFILE="$XDG_DATA_HOME/less/history"
export HISTFILE="$XDG_DATA_HOME/bash/history"
export _Z_DATA="$XDG_DATA_HOME/z/z_data"
export IPYTHONDIR="$XDG_DATA_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_DATA_HOME/jupyter"
export INPUTRC="$XDG_CONFIG_HOME/input/config"
