#!/usr/bin/env bash

atom_apps=(
  stylus
  atom-beautify
  atom-clock
  atom-live-server
  atom-math
  autocomplete-emojis
  jekyll
  jquery-snippets
  kite
  language-arduino
  language-prolog
  markdown-preview-plus
  minimap
  pdf-view
  pigments
  platformio-ide
  platomformio
  termination
)

apm install "${atom_apps[@]}"
