#!/usr/bin/env bash

echo "Installing Brew..."

# install brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# newest version of brew and packages
brew update
brew upgrade

# Install packages
brew_apps=(
  bash
  coreutils
  fish
  git
  hub
  imagesnap
  nano
  pandoc
  pandoc-citeproc
  python
  python3
  ruby
  shpotify
  sqlite
  thefuck
)

brew install "${brew_apps[@]}"
