#!/usr/bin/env bash

# first clone the bare repo in .dot directory
git clone --bare https://github.com/yochem/dotfiles.git ${HOME}/.dot

# create alias to work with for now this seperates the work tree and git dir
alias dot="git --git-dir=${HOME}/.dot/ --work-tree=${HOME}"

# checkout gets the working tree files
dot checkout

if [[ $? \eq 0 ]]; then
    echo "dotfiles installed. You might need to restart your terminal."
else
    # if git checkout returned an error, create a backup and overwrite
    mkdir -p .dotfiles-backup
    dot checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi

dot config status.showUntrackedFiles no
