#!/usr/bin/env bash

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask password
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Package managers & packages
. "$ROOT_DIR/install/brew"
. "$ROOT_DIR/install/brew-cask"
. "$ROOT_DIR/install/pip"
. "$ROOT_DIR/install/apm"

# Bunch of symlinks from files in this directory to your home directory
ln -sfv "$ROOT_DIR/bash/.aliases" ~
ln -sfv "$ROOT_DIR/bash/.bash_profile" ~
ln -sfv "$ROOT_DIR/bash/.bash_prompt" ~
ln -sfv "$ROOT_DIR/bash/.functions" ~
ln -sfv "$ROOT_DIR/git/.gitconfig" ~
ln -sfv "$ROOT_DIR/.hyper.js" ~

# RUBYGEM install/update
sudo gem update --system  # you might need to be an administrator or root

# JEKYLL install
sudo gem install jekyll bundler

# Run macOS defaults
. "$ROOT_DIR/install/.macdefaults"
