#!/usr/bin/env bash

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# # Ask password
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Package managers & packages
. "$ROOT_DIR/install/brew.sh"
. "$ROOT_DIR/install/brew-cask.sh"
. "$ROOT_DIR/install/pip.sh"

# Atom packages

# Bunch of symlinks from files in this directory to your home directory
ln -sfv "$ROOT_DIR/.bash_profile" ~
ln -sfv "$ROOT_DIR/.gitconfig" ~
ln -sfv "$ROOT_DIR/.hyper.js" ~
ln -sfv "$ROOT_DIR/.update" ~

# RUBYGEM install/update
sudo gem update --system  # you might need to be an administrator or root

# JEKYLL install
sudo gem install jekyll bundler

# Run macOS defaults
. "$ROOT_DIR/.macdefaults"
